language: ruby
cache: bundler
sudo: false

before_install:
  - rvm @global do gem uninstall bundler --all --executables
  - gem uninstall bundler --all --executables
  - gem install bundler --version '~> 1.5.2'
  - bundle --version
bundler_args: --without=development

rvm: 2.0.0
env: VAGRANT_VERSION=v1.8.1
matrix:
  include:
    - env: VAGRANT_VERSION=v1.7.2
      rack: 1.6.7
    - env: VAGRANT_VERSION=v1.6.5
      rack: 1.6.7
    - env: VAGRANT_VERSION=v1.5.4
      rack: 1.6.7
      nokogiri: 1.6.8.1
    - env: VAGRANT_VERSION=v1.4.3
      rack: 1.6.7
      nokogiri: 1.6.8.1
    - env: VAGRANT_VERSION=master
  allow_failures:
    - env: VAGRANT_VERSION=master
